### ISSUE TITLE
amazon-kinesis-client 1.13.1 breaks dynamodb-streams-kinesis-adapter

### ISSUE THREAD

**Issue by tmszdmsk** [awslabs/dynamodb-streams-kinesis-adapter#27] opened 2020-01-02 00:38 UTC
The newly released version of `amazon-kinesis-client` (`1.3.1`) is incompatible with `1.5.0` version of `dynamodb-streams-kinesis-adapter`. 

This could be fixed by removing an open-ended dependency on` amazon-kinesis-client`.

```
java.lang.NoSuchMethodError: com.amazonaws.services.kinesis.leases.impl.KinesisClientLeaseManager.<init>(Ljava/lang/String;Lcom/amazonaws/services/dynamodbv2/AmazonDynamoDB;)V
```

**Comment by jirizaloudek** [comment] 2020-01-02 14:20
This is caused by changing a constructor parameters in https://github.com/awslabs/amazon-kinesis-client/pull/656

**Comment by Cory-Bradshaw** [comment] 2020-01-07 17:19
Thanks for reporting this. Taking a look...

**Comment by aggarwal** [comment] 2020-03-31 05:05
Thanks for reporting this issue and submitting the fix. Resolving issue.

**Closed by aggarwal** 2020-03-31 05:05 UTC
